### PR TITLE
Update token.py

### PR DESCRIPTION
**Pull request by subsurfaceiodev**
This enables Google's oauth2 authentication. For example when using something like:

```
AUTH_URL = 'https://accounts.google.com/o/oauth2/v2/auth'
TOKEN_URL = 'https://oauth2.googleapis.com/token'
CLIENT_ID = 'XXXXXXXXXXXXXXXXXXXXX'

auth = DashAuthExternal(
    AUTH_URL, TOKEN_URL, CLIENT_ID,
    client_secret='YYYYYYYYYYYYYYYYYYY',
    scope='email',
)
```

### CODE REVIEW

**Comment by jamesholcombe** [comment]
Thanks for the input. I would prefer if we didn't add specfic code for certain OAuth providers, could we adapt this to allow user to access other arbitrary params that might have been returned in the token response. Possibly adding an 'extras' optional dict to the  class? and then exposing a new method to access the entire token object, called get_token_data?

**Comment by subsurfaceiodev** [comment]
That would work! Only our knowledge about programming and this module is limited to something simpler as proposed.

**Comment by jamesholcombe** [comment]
not to worry! I'll draft a release at some point in the next few days.

**Comment by jamesholcombe** [comment]
@subsurfaceiodev added get_token_data method in v1.2.0

**Pull request merged**
